export const ADD_MESSAGES = 'CHAT/ADD_MESSAGES';

export const UPDATE_TEAMS = 'LOBBY/UPDATE_TEAMS';
export const REMOVE_TEAM = 'LOBBY/REMOVE_TEAM';
export const LEAVE_TEAM = 'LOBBY/LEAVE_TEAM';
export const JOIN_TEAM = 'LOBBY/JOIN_TEAM';
export const CREATE_TEAM = 'LOBBY/CREATE_TEAM';

export const UPDATE_GAME = 'GAME/UPDATE_GAME';
