export const SOCKET_URL = 'localhost:9000';

export const SOCKET_EVENTS = {
  USER_AUTOLOGIN: 'AUTH/USER_AUTOLOGIN',
  USER_LOGIN: 'AUTH/USER_LOGIN',
  USER_LOGOUT: 'AUTH/USER_LOGOUT',
  USER_SIGNUP: 'AUTH/USER_SIGNUP',
  USERS_ONLINE: 'AUTH/USERS_ONLINE',

  SEND_MESSAGE: 'CHAT/SEND_MESSAGE',

  CREATE_TEAM: 'LOBBY/CREATE_TEAM',
  TEAM_LIST: 'LOBBY/TEAM_LIST',
  JOIN_TO_TEAM: 'LOBBY/JOIN_TO_TEAM',
  LEAVE_TEAM: 'LOBBY/LEAVE_TEAM',
  READY_TO_START: 'LOBBY/READY_TO_START',

  START_GAME: 'GAME/START_GAME',
  END_GAME: 'GAME/END_GAME',
  GAME_MOVE: 'GAME/MOVE',
  GAME_LEAVE_SHIP: 'GAME/LEAVE_SHIP',
};
